version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    networks:
      - app-network
    container_name: redisinsight

networks:
  app-network:
    driver: bridge